import { Tag, CustomerArchetype, Card } from './types';

export const TAGS: Tag[] = ['safety', 'economy', 'comfort', 'performance', 'technology'];

export const CUSTOMER_ARCHETYPES: Record<string, CustomerArchetype> = {
  'Young Family': {
    name: 'Young Family',
    description: 'Looking for something safe and spacious.',
    priorities: ['safety', 'comfort'],
    objectionType: 'price',
    behavior: 'Fires objection every 2 turns',
    baseBudget: [8000, 12000],
    objectionStrength: [500, 600],
  },
  'Commuter': {
    name: 'Commuter',
    description: 'Needs efficiency and tech for the long drive.',
    priorities: ['economy', 'technology'],
    objectionType: 'features',
    behavior: 'Fires objection on missed offers',
    baseBudget: [10000, 15000],
    objectionStrength: [600, 700],
  },
  'Enthusiast': {
    name: 'Enthusiast',
    description: 'Wants power and the latest gadgets.',
    priorities: ['performance', 'technology'],
    objectionType: 'practicality',
    behavior: 'Fires objection on missed offers',
    baseBudget: [15000, 25000],
    objectionStrength: [700, 800],
  },
  'Skeptic': {
    name: 'Skeptic',
    description: 'Hard to please, values reliability and cost.',
    priorities: ['safety', 'economy'],
    objectionType: 'trust',
    behavior: 'Fires objection every turn',
    baseBudget: [8000, 12000],
    objectionStrength: [800, 1000],
  },
  'Fleet Buyer': {
    name: 'Fleet Buyer',
    description: 'Buying for business, values utility and safety.',
    priorities: ['economy', 'safety'],
    objectionType: 'price',
    behavior: 'Never walks but haggles hard',
    baseBudget: [40000, 60000],
    objectionStrength: [1000, 1500],
  },
};

export const STARTER_DECK: Card[] = [
  {
    id: 'civic-lx-1',
    name: '2024 Civic LX',
    type: 'product',
    energyCost: 1,
    description: 'A reliable starter vehicle.',
    value: 8000,
    slots: 3,
  },
  {
    id: 'old-truck-1',
    name: '98 Work Truck',
    type: 'product',
    energyCost: 1,
    description: 'Seen better days, but it runs.',
    value: 4000,
    slots: 2,
  },
  {
    id: 'reliable-build-1',
    name: 'Safety Package',
    type: 'value',
    energyCost: 1,
    description: 'Adds safety features.',
    value: 200,
    tags: ['safety'],
  },
  {
    id: 'standard-engine-1',
    name: 'Economy Tune',
    type: 'value',
    energyCost: 1,
    description: 'Fuel efficient.',
    value: 200,
    tags: ['economy'],
  },
  {
    id: 'comfortable-interior',
    name: 'Comfort Trim',
    type: 'value',
    energyCost: 1,
    description: 'Premium seating.',
    value: 200,
    tags: ['comfort'],
  },
  {
    id: 'premium-markup-1',
    name: 'Dealer Markup',
    type: 'value',
    energyCost: 1,
    description: 'Pure profit.',
    value: 800,
  },
  {
    id: 'winter-eh-1',
    name: 'Hell of a Winter Eh?',
    type: 'rapport',
    energyCost: 1,
    description: 'Build rapport.',
    value: 400,
  },
  {
    id: 'compliment-1',
    name: 'Throw them a compliment',
    type: 'rapport',
    energyCost: 0,
    description: 'A kind word.',
    value: 200,
  },
  {
    id: 'rapport-extra-1',
    name: 'Small Talk',
    type: 'rapport',
    energyCost: 1,
    description: 'Casual conversation.',
    value: 300,
  },
  {
    id: 'action-offer-1',
    name: 'Make an Offer',
    type: 'discovery', // Using discovery type for general actions for now
    energyCost: 1,
    description: 'Select a shelved product to offer to the customer.',
  },
  {
    id: 'action-sacrifice-1',
    name: 'Sacrifice for Rapport',
    type: 'discovery',
    energyCost: 1,
    description: 'Sacrifice a shelved product for immediate Rapport (10% value).',
  },
];
